# Jekyll config for
# https://runxel.github.io | https://runxel.xyz

title: runxel
#email: 
description: >-
  Homepage of runxel.
# baseurl: 
github_username: runxel
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
